sudo: false
language: node_js
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
before_script:
  - mkdir tmp
  - export TMPDIR=$(pwd)/tmp
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
